zookeeper:
  build: mesos
  # image: mesos
  ports:
    - "49181:2181"
  command: /usr/share/zookeeper/bin/zkServer.sh start-foreground
master:
  build: mesos-master
  hostname: master
  ports:
    - "15050:5050"
    # - "49773:3773"
    # - "49772:3772"
    # - "49627:6627"
    # - "14400:4400"
    # - "18080:8080"
    # - "19080:8772"
# storm ui is using port 8772 as per storm.yaml
  links:
    - zookeeper:zookeeper
#    - slave:slave
